language: bash

# It would be possible to use the container-based infrastructure if
# it ran trusty. However, it doesn't and wget is too old to use for
# HTTPS to buildroot.net.
sudo: required
dist: trusty

# Install dependencies
addons:
  apt:
    packages:
    - bc
    - libssl-dev

# Cache downloaded files between builds
cache:
    directories:
      - $HOME/.nerves/cache/buildroot

# Build the official configurations
env:
  matrix:
  - CI_DEFCONFIG_DIR=nerves_system_qemu_arm CI_DEFCONFIG=elixir
  - CI_DEFCONFIG_DIR=nerves_system_bbb CI_DEFCONFIG=elixir
  - CI_DEFCONFIG_DIR=nerves_system_ev3 CI_DEFCONFIG=elixir
  - CI_DEFCONFIG_DIR=nerves_system_rpi CI_DEFCONFIG=elixir
  - CI_DEFCONFIG_DIR=nerves_system_rpi2 CI_DEFCONFIG=elixir
  - CI_DEFCONFIG_DIR=nerves_system_rpi3 CI_DEFCONFIG=elixir
  - CI_DEFCONFIG_DIR=nerves_system_galileo CI_DEFCONFIG=elixir

# Inspect the cache and build
script:
    - ls -las $HOME/.nerves/cache/buildroot || true
    - ./scripts/ci-build.sh

# Deploy the build products
before_deploy:
    - ./scripts/ci-deploy.sh
deploy:
  # Deploy tagged releases to GitHub
  - provider: releases
    api_key: $GITHUB_API_KEY
    file:
      - "artifacts/$CI_DEFCONFIG_DIR-$CI_DEFCONFIG-$TRAVIS_TAG.tar.gz"
      - "artifacts/$CI_DEFCONFIG_DIR-$CI_DEFCONFIG-$TRAVIS_TAG.fw"
    skip_cleanup: true
    on:
      repo: nerves-project/nerves_system_br
      tags: true
  # Copy all build products to S3
  - provider: s3
    access_key_id: $ARTIFACTS_KEY
    secret_access_key: $ARTIFACTS_SECRET
    bucket: $ARTIFACTS_BUCKET
    skip_cleanup: true
    local_dir: artifacts
    upload-dir: nerves_system_br
    storage_class: "REDUCED_REDUNDANCY"  # See https://github.com/travis-ci/dpl/issues/291
    on:
      repo: nerves-project/nerves_system_br
      all_branches: true

# Display build log on failure
after_failure:
    - tail -n 1000 ./ci/build.log
